DROP TABLE IF EXISTS PLAYERS;
DROP TABLE IF EXISTS TEAMS;

CREATE TABLE TEAMS (
  TEAM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  ACRONYM VARCHAR(10) NOT NULL,
  BUDGET NUMERIC(19,2) NOT NULL
);

CREATE TABLE PLAYERS (
  PLAYER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  POSITION VARCHAR(250) NOT NULL,
  BUDGET NUMERIC(19,2),
  TEAM_ID BIGINT FOREIGN KEY REFERENCES TEAMS ON DELETE SET NULL
);